#Packages to install


#Install required packages
install.packages("base")
install.packages("bfast")
install.packages("forecast")
install.packages("GISTools")
install.packages("Graphics")
install.packages("grDevices")
install.packages("methods")
install.packages("plotrix")
install.packages("purr")
install.packages("raster")
install.packages("stats")
install.packages("Utils")
install.packages("Viridis")
install.packages("viridisLite")
install.packages("trend")

library("base")
library("bfast")
library("forecast")
library("GISTools")
library("graphics")
library("grDevices")
library("methods")
library("plotrix")
library("purrr")
library("raster")
library("stats")
library("utils")
library("viridis")
library("viridisLite")
library("trend")
